#version 460

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// Uniforms for filling buffer
layout(set = 0, binding = 0) uniform float fillValue;
layout(set = 0, binding = 1) uniform uint bufferSize;

// Buffer for the output array
layout(set = 0, binding = 2) buffer OutputBuffer {
    float output[];
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < bufferSize) {
        output[idx] = fillValue;
    }
}
